import sys
sys.path.append('.')
from backend.retrieval.signal_extractor import extract_signals

sample = """
# Built to make you extraordinarily productive, Cursor is the best coding agent. sh/updates/download/golden/darwin-universal/cursor/3. com/agents) Request a demo →  This element contains an interactive demo for sighted users showing multiple Cursor interfaces: Cursor Desktop interface, Cursor CLI interface. The interface is displayed over a subtle, solid brand background. Cursor Desktop Get Cursor In Progress 2 Analyze Tab vs Agent Usage Patterns Fetching data Plan Mission Control Generating plan Ready for Review 4 Build Landing Page now Done. Fonts preload in the head, critical CSS is inlined, and I added a color-scheme meta tag so dark mode renders insta PyTorch MNIST Experiments 10m PyTorch MNIST Experiments Set up Cursor Rules for  30m Set up Cursor Rules for  Bioinformatics Tools 45m +135-21·Bioinformatics Tools  Acme Labs Software creation is changing. We are a group of researchers, engineers, and technologists inventing at the edge of what's useful and possible. See projectsJoin our team → 2026 Secure codebase indexing Published 2026 Semantic search Published 2025 Reinforcement learning Published 2024 Shadow workspaces Published 2024 Multi-agent collaboration Published 2023 Context-aware completions Published 2023 Intelligent code navigation Published 2022 Fast inference optimization Published 2022 Language model fine-tuning Published Tagline · span Build Landing Page make a landing page based on attached docs explaining what we do Read about-acme. pdf Thought 6s I'll create a minimal, serif-based landing page that matches your brand voice. Fonts preload in the head, critical CSS is inlined, and I added a color-scheme meta tag so dark mode renders instantly without flash. 5 Cursor CLI Get CLI Cursor Agent ~/cursor/cursor-web Analyze Tab vs Agent Usage Patterns Help me understand how teams split their focus between the tab view and the agents panel across our workspaces. ⬢ T h o u g h t 7 s ⬢ R e v i e w e d w o r k s p a c e u s a g e e x p o r t s a n d h i s t o r i c a l e n g a g e m e n t n o t e s I'll build an analytics toolkit that highlights tab versus agent adoption and switching behavior: summary. py+150-0 Next I'll normalize the interaction labels and add session tagging so product can filter specific cohorts: segmentation. py+94-0 Time to stitch everything together with a report helper that combines the key metrics: report. py+40-0 I'll add tests to lock in the behaviour using a representative sample from last week's export: test_usage. py+90 All set! We now track focus share, switching rates, and rolling engagement so PMs can compare tab-first and agent-first workflows in seconds. 5 / for commands · @ for files #
"""

signals = extract_signals(sample)
for sig in signals.get('launch_signals', []):
    print(sig)
