from typing import Sequence
import uuid
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_, desc

from backend.database.models import StrategicSignalRecord
from backend.signals.models import StrategicSignal
from backend.signals.enums import SignalSeverity
from backend.temporal.enums import TemporalChangeCategory, TemporalChangeDirection, TemporalConfidenceLevel

class StrategicSignalRepository:
    """
    Persistence layer for Strategic Signals.
    Handles storage and retrieval of deterministic intelligence artifacts.
    Never manages transaction lifecycles (no commit, no rollback).
    """
    def __init__(self, session: AsyncSession):
        self.session = session

    def _to_record(self, signal: StrategicSignal, organization_id: uuid.UUID) -> StrategicSignalRecord:
        return StrategicSignalRecord(
            signal_id=signal.signal_id,
            organization_id=organization_id,
            company_name=signal.company_name,
            category=signal.category.value,
            direction=signal.direction.value,
            summary=signal.summary,
            business_impact=signal.business_impact,
            confidence_score=signal.confidence_score,
            confidence_level=signal.confidence_level.value,
            severity=signal.severity.value,
            evidence=[ev.model_dump() for ev in signal.evidence],
            originating_run_id=signal.originating_run_id,
            prompt_version=signal.prompt_version,
            model_name=signal.model_name,
            analysis_version=signal.analysis_version,
            signal_source=signal.signal_source,
            signal_fingerprint=signal.signal_fingerprint,
            detected_at=signal.detected_at
        )

    def _to_model(self, record: StrategicSignalRecord) -> StrategicSignal:
        return StrategicSignal(
            signal_id=record.signal_id,
            signal_fingerprint=record.signal_fingerprint,
            company_name=record.company_name,
            category=TemporalChangeCategory(record.category),
            direction=TemporalChangeDirection(record.direction),
            summary=record.summary,
            business_impact=record.business_impact,
            confidence_score=record.confidence_score,
            confidence_level=TemporalConfidenceLevel(record.confidence_level),
            severity=SignalSeverity(record.severity),
            evidence=record.evidence, # pydantic parses list of dicts to models
            originating_run_id=record.originating_run_id,
            prompt_version=record.prompt_version,
            model_name=record.model_name,
            analysis_version=record.analysis_version,
            signal_source=record.signal_source,
            detected_at=record.detected_at
        )

    async def save(self, signals: list[StrategicSignal], organization_id: uuid.UUID) -> int:
        """
        Saves a batch of strategic signals.
        Silently skips signals that already exist (based on signal_id).
        """
        if not signals:
            return 0
            
        inserted_count = 0
        for signal in signals:
            # Idempotency check
            exists = await self.exists(signal.signal_id)
            if exists:
                continue
                
            record = self._to_record(signal, organization_id)
            self.session.add(record)
            inserted_count += 1
            
        return inserted_count

    async def exists(self, signal_id: uuid.UUID) -> bool:
        """Checks if a signal exists by ID."""
        stmt = select(StrategicSignalRecord.signal_id).where(
            StrategicSignalRecord.signal_id == signal_id
        )
        result = await self.session.execute(stmt)
        return result.first() is not None

    async def get_by_company(self, company_name: str) -> list[StrategicSignal]:
        """Retrieves all signals for a company in chronological order."""
        stmt = select(StrategicSignalRecord).where(
            StrategicSignalRecord.company_name == company_name
        ).order_by(StrategicSignalRecord.detected_at.asc())
        
        result = await self.session.execute(stmt)
        records = result.scalars().all()
        return [self._to_model(r) for r in records]

    async def get_by_run(self, run_id: str) -> list[StrategicSignal]:
        """Retrieves all signals generated by a specific run."""
        stmt = select(StrategicSignalRecord).where(
            StrategicSignalRecord.originating_run_id == run_id
        ).order_by(StrategicSignalRecord.detected_at.asc())
        
        result = await self.session.execute(stmt)
        records = result.scalars().all()
        return [self._to_model(r) for r in records]

    async def get_by_fingerprint(self, fingerprint: str) -> list[StrategicSignal]:
        """Retrieves all signals sharing a semantic fingerprint."""
        stmt = select(StrategicSignalRecord).where(
            StrategicSignalRecord.signal_fingerprint == fingerprint
        ).order_by(StrategicSignalRecord.detected_at.asc())
        
        result = await self.session.execute(stmt)
        records = result.scalars().all()
        return [self._to_model(r) for r in records]
