"""add_watchlist_schedule_fields

Revision ID: 5de7c8d6acf9
Revises: 5e98132936f8
Create Date: 2026-06-07 14:43:16.852870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de7c8d6acf9'
down_revision: Union[str, None] = '5e98132936f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watchlists",
        sa.Column(
            "monitoring_frequency",
            sa.String(length=20),
            nullable=False,
            server_default="DAILY",
        ),
    )
    op.add_column('watchlists', sa.Column('last_monitored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('watchlists', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_watchlists_next_run_at'), 'watchlists', ['next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_next_run_at'), table_name='watchlists')
    op.drop_column('watchlists', 'next_run_at')
    op.drop_column('watchlists', 'last_monitored_at')
    op.drop_column('watchlists', 'monitoring_frequency')
    # ### end Alembic commands ###
