"""add_notification_events

Revision ID: 5e98132936f8
Revises: 8037b6754a97
Create Date: 2026-06-07 14:09:36.259741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e98132936f8'
down_revision: Union[str, None] = '8037b6754a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=500), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_company_name'), 'notification_events', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_events_company_name'), table_name='notification_events')
    op.drop_table('notification_events')
    # ### end Alembic commands ###
