"""add_alerts_suppressed_to_monitoring_runs

Revision ID: 8037b6754a97
Revises: ee10a5e2c5e7
Create Date: 2026-06-07 13:38:18.465682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8037b6754a97'
down_revision: Union[str, None] = 'ee10a5e2c5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitoring_runs",
        sa.Column(
            "alerts_suppressed",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_runs', 'alerts_suppressed')
    # ### end Alembic commands ###
