"""create_strategic_signals

Revision ID: 811b3f992bf1
Revises: ef3c8eae88e7
Create Date: 2026-07-08 16:48:34.452547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '811b3f992bf1'
down_revision: Union[str, None] = 'ef3c8eae88e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategic_signals',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('originating_run_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('analysis_version', sa.String(length=50), nullable=False),
    sa.Column('signal_source', sa.String(length=100), nullable=False),
    sa.Column('signal_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['originating_run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_strategic_signals_category'), 'strategic_signals', ['category'], unique=False)
    op.create_index('ix_strategic_signals_company_detected', 'strategic_signals', ['company_name', 'detected_at'], unique=False)
    op.create_index(op.f('ix_strategic_signals_company_name'), 'strategic_signals', ['company_name'], unique=False)
    op.create_index(op.f('ix_strategic_signals_detected_at'), 'strategic_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_strategic_signals_organization_id'), 'strategic_signals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_strategic_signals_originating_run_id'), 'strategic_signals', ['originating_run_id'], unique=False)
    op.create_index(op.f('ix_strategic_signals_signal_fingerprint'), 'strategic_signals', ['signal_fingerprint'], unique=False)
    op.alter_column('alert_history', 'reasons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('alert_history', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('90'))
    op.alter_column('alert_history', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.add_column('competitor_analyses', sa.Column('originating_run_id', sa.String(), nullable=True))
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_constraint('runs_user_id_fkey', 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('watchlist_competitors', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('watchlist_competitors', 'monitoring_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlist_competitors', 'monitoring_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('watchlist_competitors', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key('runs_user_id_fkey', 'runs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('competitor_analyses', 'originating_run_id')
    op.alter_column('alert_history', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('alert_history', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('90'))
    op.alter_column('alert_history', 'reasons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_strategic_signals_signal_fingerprint'), table_name='strategic_signals')
    op.drop_index(op.f('ix_strategic_signals_originating_run_id'), table_name='strategic_signals')
    op.drop_index(op.f('ix_strategic_signals_organization_id'), table_name='strategic_signals')
    op.drop_index(op.f('ix_strategic_signals_detected_at'), table_name='strategic_signals')
    op.drop_index(op.f('ix_strategic_signals_company_name'), table_name='strategic_signals')
    op.drop_index('ix_strategic_signals_company_detected', table_name='strategic_signals')
    op.drop_index(op.f('ix_strategic_signals_category'), table_name='strategic_signals')
    op.drop_table('strategic_signals')
    # ### end Alembic commands ###
