"""add_celery_task_id_to_monitoring_runs

Revision ID: ee10a5e2c5e7
Revises: b96b288c5bc8
Create Date: 2026-06-06 15:44:07.217716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee10a5e2c5e7'
down_revision: Union[str, None] = 'b96b288c5bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_runs', sa.Column('celery_task_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_monitoring_runs_celery_task_id'), 'monitoring_runs', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_runs_celery_task_id'), table_name='monitoring_runs')
    op.drop_column('monitoring_runs', 'celery_task_id')
    # ### end Alembic commands ###
