"""create intelligence embeddings

Revision ID: ef3c8eae88e7
Revises: ce7b1c51b293
Create Date: 2026-06-25 20:52:58.722705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'ef3c8eae88e7'
down_revision: Union[str, None] = 'ce7b1c51b293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.Enum('ANALYSIS', 'DRIFT_INTERPRETATION', 'COMPARISON_BRIEF', name='embedding_source_type_enum'), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_type', sa.Enum('EXECUTIVE_BRIEFING', 'ANALYST_NOTE', 'STRUCTURED_SUMMARIES', 'DRIFT_INTERPRETATION', 'COMPARISON_SUMMARY', name='chunk_type_enum'), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_embeddings_company_time', 'intelligence_embeddings', ['company_name', 'analyzed_at'], unique=False)
    op.create_index('ix_embeddings_source', 'intelligence_embeddings', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_intelligence_embeddings_analyzed_at'), 'intelligence_embeddings', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_intelligence_embeddings_company_name'), 'intelligence_embeddings', ['company_name'], unique=False)
    op.create_index(op.f('ix_intelligence_embeddings_organization_id'), 'intelligence_embeddings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_intelligence_embeddings_run_id'), 'intelligence_embeddings', ['run_id'], unique=False)
    op.create_index(op.f('ix_intelligence_embeddings_source_id'), 'intelligence_embeddings', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_embeddings_source_id'), table_name='intelligence_embeddings')
    op.drop_index(op.f('ix_intelligence_embeddings_run_id'), table_name='intelligence_embeddings')
    op.drop_index(op.f('ix_intelligence_embeddings_organization_id'), table_name='intelligence_embeddings')
    op.drop_index(op.f('ix_intelligence_embeddings_company_name'), table_name='intelligence_embeddings')
    op.drop_index(op.f('ix_intelligence_embeddings_analyzed_at'), table_name='intelligence_embeddings')
    op.drop_index('ix_embeddings_source', table_name='intelligence_embeddings')
    op.drop_index('ix_embeddings_company_time', table_name='intelligence_embeddings')
    op.drop_table('intelligence_embeddings')
    # ### end Alembic commands ###
